# Assignment 1- Linear Algebra: Questions 1, 2, 5

__Tapaswi Satyapanthi__ <br>
_satyapanthi.t@northeastern.edu_

__Importing necessary library__

In [1]:
import numpy as np
from numpy.linalg import matrix_rank

## Question 1

__Matrix initialisation__

In [2]:
# Creating matrix A or 2d array with the help of numpy's
# randint function by passing tuple, containing matrix dimentions
# to the size parameter
matrix_A = np.random.randint(-10, 10, size=(5, 2))

# Creating vector X by using numpy's randint function
vector_x = np.random.randint(-10, 10, size=(2,1))

# Diagonal matrix B with dimentions 5x5 having 1 to 5 on diagonal
matrix_B = np.diag([2, 1, 3, 4, 5])

print(f"Matrix A: \n{matrix_A}")
print(f"\nMatrix B: \n{matrix_B}")
print(f"\nVector X: \n{vector_x}")

Matrix A: 
[[ 4  0]
 [ 4  6]
 [ 2  6]
 [-8 -4]
 [-4  9]]

Matrix B: 
[[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Vector X: 
[[-2]
 [ 2]]


#### Matrix-Vector product: Ax

In [3]:
Ax_product = np.dot(matrix_A, vector_x)

print(f"Matrix - Vector(Ax) product: \n{Ax_product}")

Matrix - Vector(Ax) product: 
[[-8]
 [ 4]
 [ 8]
 [ 8]
 [26]]


#### Matrix-Matrix product: BA

In [4]:
BA_product = np.dot(matrix_B, matrix_A)

print(f"Matrix - Matrix(BA) product: \n{BA_product}")

Matrix - Matrix(BA) product: 
[[  8   0]
 [  4   6]
 [  6  18]
 [-32 -16]
 [-20  45]]


<br>

# Question 2

In [5]:
# Calculating rank of matrix A
rank_A = matrix_rank(matrix_A)

# Calculating rank of matrix B
rank_B = matrix_rank(matrix_B)

# Calculating rank of matrix BA
rank_BA = matrix_rank(np.dot(matrix_B,matrix_A))

print(f"Rank of matrix A: {rank_A}")
print(f"Rank of matrix B: {rank_B}")
print(f"Rank of matrix BA: {rank_BA}")

Rank of matrix A: 2
Rank of matrix B: 5
Rank of matrix BA: 2


### What about the rank of BA? Are they differrent? Why?

Here rank of the matrix <code>BA</code> is not equal to the rank of matrix <code>B</code> but equal to the rank of matrix <code>A</code> because the <code>rank(BA)</code> is determined by the following relationship: 

<code>rank(BA)</code> is minimum of the ranks of the matrices <code>B</code> and <code>A</code> 
i.e. <code>rank(BA) <= minimum(rank(B), rank(A))</code>

Hence, the rank of matrix <code>BA</code> will not be 5, same as matrix <code>B</code>, because the minimum of the ranks of <code>B</code> and <code>A</code> is 2, the rank of the matrix <code>A</code>. 

So, the rank of the matrix <code>BA</code> <= rank of <code>A</code>, in this case equal to <code>A</code>, i.e. 2.


<br>

# Question 5

#### Initializing matrices for question 5

In [6]:
# Initializing matrices A, B & C
A = np.array([[-2,  1,  8],
              [-1, -1,  7],
              [ 3,  0,  4]])
              
B = np.array([[ 5,  0, -7],
              [ 6,  3, -9],
              [-2, -2,  0]])
              
C = np.array([[ 6,  3, -1],
              [ 2,  4,  5],
              [-1, -1,  8]])

#### Matrix Concatenation and vector b initialization

In [7]:
# Concatenating matrices A, B & C
D = np.concatenate((A, B, C))
print(f"Concatenated matrix D: \n{D}")

# Initializing vector b and transposing it
b = np.array([[3, -10, 2]]).T
print(f"\nVector b after transposing: \n{b}")

Concatenated matrix D: 
[[-2  1  8]
 [-1 -1  7]
 [ 3  0  4]
 [ 5  0 -7]
 [ 6  3 -9]
 [-2 -2  0]
 [ 6  3 -1]
 [ 2  4  5]
 [-1 -1  8]]

Vector b after transposing: 
[[  3]
 [-10]
 [  2]]


#### Least Square solution

In [8]:
# Finding the least square solution
least_square = np.linalg.lstsq(D.T,b, rcond=None)[0]

print(f"Least Square solution: \n{least_square}")

Least Square solution: 
[[-0.6588419 ]
 [ 0.79125205]
 [ 1.2848211 ]
 [ 1.12195654]
 [-0.49220611]
 [ 0.53822844]
 [ 0.10452284]
 [-1.36113905]
 [ 0.86584317]]
