# Assignment 1: Questions 1, 2, 5

__Tapaswi Satyapanthi__ <br>
_satyapanthi.t@northeastern.edu_

## Problem 1

In [1]:
import numpy as np

__Matrix initialisation__

In [2]:
# Creating matrix A or 2d array with the help of numpy's
# randint function by passing tuple, containing matrix dimentions
# to the size parameter
matrix_A = np.random.randint(-10, 10, size=(5, 2))

# Creating vector X by using numpy's randint function
# Since this is a vector, I'm using only a list
vector_x = np.random.randint(-10, 10, size=2)

# Diagonal matrix B with dimentions 5x5 having 1 to 5 on diagonal
matrix_B = np.diag([2, 1, 3, 4, 5])

print(f"Matrix A: \n{matrix_A}")
print(f"\nMatrix B: \n{matrix_B}")
print(f"\nVector X: \n{vector_x}")

Matrix A: 
[[ -1  -2]
 [ -7  -6]
 [  2  -1]
 [  4   0]
 [  4 -10]]

Matrix B: 
[[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Vector X: 
[8 3]


In [3]:
# Function to add and multiply rows
def add_rows(tuples):
    return sum((tuple[0]*tuple[1]) for tuple in tuples)

## Matrix-Vector product: Ax

__Product using custom logic__

In [4]:
# Function to calculate matrix-vector product
def matrix_vector_product(matrixA, vectorX):
    # if
    if matrixA.shape[1] != vectorX.shape[0]:
        return "Product not possible, please check the dimensions."

    # initialising the answer vector as an empty array
    ans_vector = []

    # logic to calculate matrix-vector product
    for row in matrix_A:
        ans_vector.append(add_rows(tuple(zip(row, vector_x))))

    return ans_vector

In [5]:
Ax_product = matrix_vector_product(matrix_A, vector_x)

print(f"Matrix - Vector(Ax) product using custom logic: \n{Ax_product}")

Matrix - Vector(Ax) product using custom logic: 
[-4, -1, -7, -7, 1]


__Product using numpy's _dot_ function__

In [6]:
Ax_product = np.dot(matrix_A, vector_x)

print(f"Matrix - Vector(Ax) product using numpy.dot function: \n{Ax_product}")

Matrix - Vector(Ax) product using numpy.dot function: 
[-4 -1 -7 -7  1]


## Matrix-Matrix product: BA

__Product using custom logic__

In [7]:
# Function to calculate matrix-matrix product
def matrix_matrix_product(matrix1, matrix2):

    # If no. of columns of first matrix and no. of rows of second matrix
    # doesn't match, then the product is not possible so.
    if matrix1.shape[1] != matrix2.shape[0]:
        return "Product not possible, please check the dimensions."

    # Extracting the dimensions of the resultant matrix
    ans_matrix_row = matrix1.shape[0] # no. of rows of first matrix
    ans_matrix_col = matrix2.shape[1] # no. of columns of second matrix

    # Initialising the resultant matrix with zeros
    ans_matrix = np.zeros((ans_matrix_row, ans_matrix_col), dtype=int)

    # logic to multiply two matrices
    for row_index in range(len(matrix1)):
        for col_index in range(len(matrix2[0])):
            ans_matrix[row_index][col_index] \
                = add_rows(tuple(zip(matrix1[row_index], matrix2[:, col_index])))

    return ans_matrix


In [8]:
BA_product = matrix_matrix_product(matrix_B, matrix_A)

print(f"Matrix - Matrix(BA) product using custom logic: \n{BA_product}")

Matrix - Matrix(BA) product using custom logic: 
[[ 18  -8]
 [  0  -1]
 [ -9 -21]
 [ 36 -28]
 [-30   5]]


__Product using numpy's _dot_ function__

In [9]:
BA_product = np.dot(matrix_B, matrix_A)

print(f"Matrix - Matrix(BA) product using numpy.dot function: \n{BA_product}")

Matrix - Matrix(BA) product using numpy.dot function: 
[[ 18  -8]
 [  0  -1]
 [ -9 -21]
 [ 36 -28]
 [-30   5]]


# Problem 2

In [10]:
from numpy.linalg import matrix_rank

In [21]:
# Calculating rank of matrix A
rank_A = matrix_rank(matrix_A)

# Calculating rank of matrix B
rank_B = matrix_rank(matrix_B)

# Calculating rank of matrix BA
rank_BA = matrix_rank(np.dot(matrix_B,matrix_A))

print(f"Rank of matrix A: {rank_A}")
print(f"Rank of matrix B: {rank_B}")
print(f"Rank of matrix BA: {rank_BA}")

Rank of matrix A: 2
Rank of matrix B: 5
Rank of matrix BA: 2


### What about the rank of BA? Are they differrent? Why?

Here rank of the matrix BA is not equal to that of matrix B because the rank(BA) is determined by the following relationship: 

rank(BA) is minimum of the ranks of the matrices B and A 
i.e. rank(BA) <= minimum(rank(B), rank(A)).

Hence, the rank of matrix BA will not be 5, same as matrix B, because the minimum of the ranks of B and A is 2, the rank of the matrix A. So, the rank of the matrix BA <= rank of A, in this case equal to A, i.e. 2.


# Problem 5

__Initialising matrices for problem 5__

In [13]:
A = np.array([[-2,  1,  8],
              [-1, -1,  7],
              [ 3,  0,  4]])
              
B = np.array([[ 5,  0, -7],
              [ 6,  3, -9],
              [-2, -2,  0]])
              
C = np.array([[ 6,  3, -1],
              [ 2,  4,  5],
              [-1, -1,  8]])

In [14]:
D = np.concatenate((A, B, C))
D

array([[-2,  1,  8],
       [-1, -1,  7],
       [ 3,  0,  4],
       [ 5,  0, -7],
       [ 6,  3, -9],
       [-2, -2,  0],
       [ 6,  3, -1],
       [ 2,  4,  5],
       [-1, -1,  8]])

In [15]:
b = np.array([3, -10, 2])

In [16]:
x, res, rank, s = np.linalg.lstsq(D.T,b, rcond=None)
print(f"x: {x},\nres: {res},\nrank: {rank},\ns: {s}")

x: [-0.6588419   0.79125205  1.2848211   1.12195654 -0.49220611  0.53822844
  0.10452284 -1.36113905  0.86584317],
res: [],
rank: 3,
s: [19.80790713 10.13080337  3.87474364]
