In [1]:
import numpy as np

In [2]:
A = np.random.randint(20, size=(5,3))
B = np.random.randint(5, size=(3,2))

print("Matrix A: ",A)
print("Matrix B: ",B)

C = np.diag([1,2,3,4,5])
print("Matrix C: ", C)

Matrix A:  [[13 10  0]
 [19 19 11]
 [15 16  9]
 [ 0 18  6]
 [ 9  2  0]]
Matrix B:  [[0 2]
 [0 2]
 [1 2]]
Matrix C:  [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
AB = np.matmul(A,B)
print(AB)

[[ 0 46]
 [11 98]
 [ 9 80]
 [ 6 48]
 [ 0 22]]


In [4]:
ab = np.dot(A,B)
print(ab)

[[ 0 46]
 [11 98]
 [ 9 80]
 [ 6 48]
 [ 0 22]]


In [5]:
BA = np.matmul(B,A)
print(BA)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 2)